name: uav-flowprop
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - opencv
  - matplotlib
  - scipy
  - h5py
  - tqdm
  - pyyaml
  - pandas
  - einops
  - pillow
  - pytest
  - huggingface_hub
  - safetensors
  - pip:
      - imageio
      - gdown
